backend:
  name: git-gateway

publish_mode: editorial_workflow

media_library:
  name: cloudinary

  config:
    cloud_name: cc-co-dance-complex
    api_key: 568677699738745

media_folder: "static/images/uploads"
public_folder: "images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    delete: false
    files:
      - name: "home"
        label: "Home"
        file: "content/_index.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - label: "COVID Level"
            name: "covidlevel"
            widget: "select"
            required: false
            options:
              - { label: "Red", value: "red" }
              - { label: "Yellow", value: "yellow" }
              - { label: "Green", value: "green" }
          - { label: Headline, name: headline, widget: string }
          - label: "Alert"
            name: "alert"
            widget: "object"
            collapsed: true
            required: false
            fields:
              - { label: "Enabled", name: "enabled", widget: "boolean" }
              - { label: Title, name: title, widget: string, required: false }
              - { label: Description, name: description, widget: string, required: false }
              - { label: URL, name: url, widget: string, required: false }
          - label: "Carousel Images"
            name: "galleryImages"
            widget: "list"
            field:
              label: 'Image'
              name: 'image'
              widget: 'image'
              media_library:
                config:
                  default_transformations:
                    -   - fetch_format: auto
                          quality: auto:best
                          height: 700
                          crop: scale
          - { label: 'About Us content', name: 'aboutUs', widget: 'markdown' }
          - label: "Number of Events"
            name: "eventnum"
            widget: "number"
            valueType: "int"
            default: 3
            min: 0
          - label: "Partnerships"
            label_singular: "Partnership"
            name: "partnerships"
            required: false
            widget: "list"
            field:
              label: "Partner"
              name: "partner"
              widget: "object"
              fields:
                - { label: "Name", name: "name", widget: "string", required: false }
                - { label: "Logo", name: "logo", widget: "image", required: false }
                - { label: "URL", name: "url", widget: "string", required: false }
      - name: "company"
        label: "Company"
        file: "content/company/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Short Description", name: "description", widget: "string"}
          - { label: "CMS", name: "cms", widget: "hidden", default: "false"}
          - { label: "Content", name: "body", widget: "markdown"}
      - name: "resources"
        label: "Resources"
        file: "content/resources/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Short Description", name: "description", widget: "string", required: false }
          - { label: "Page Content", name: "body", widget: "markdown"}
          - label: Header Photo
            name: photo
            widget: image
            required: false
          - name: 'resources'
            label: 'Resources'
            label_singular: 'Resource'
            summary: '{{fields.section.header}}'
            widget: 'list'
            fields:
              - name: 'section'
                label: 'Section'
                widget: object
                fields:
                  - { label: Header, name: header, widget: string }
                  - name: 'items'
                    label: 'Resource Items'
                    label_singular: 'Resource'
                    widget: 'list'
                    types:
                      - name: 'document'
                        label: 'Document'
                        widget: 'object'
                        summary: '{{fields.title}}'
                        fields:
                          - { label: Title, name: title, widget: string}
                          - { label: Document, name: url, widget: file }
                      - name: 'url'
                        label: 'URL'
                        widget: 'object'
                        summary: '{{fields.title}}'
                        fields:
                          - { label: Title, name: title, widget: string}
                          - { label: URL, name: url, widget: string }
      - name: "covid-19"
        label: "COVID-19 Information"
        file: "content/covid-19/_index.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: "Is Draft?", name: "draft", widget: "boolean"}
          - { label: Content, name: body, widget: markdown }
          - name: 'resources'
            label: 'Resources'
            label_singular: 'Resource'
            summary: '{{fields.section.header}}'
            widget: 'list'
            fields:
              - name: 'section'
                label: 'Section'
                widget: object
                fields:
                  - { label: Header, name: header, widget: string }
                  - name: 'items'
                    label: 'Resource Items'
                    label_singular: 'Resource'
                    widget: 'list'
                    types:
                      - name: 'document'
                        label: 'Document'
                        widget: 'object'
                        summary: '{{fields.title}}'
                        fields:
                          - { label: Title, name: title, widget: string}
                          - { label: Document, name: url, widget: file }
                      - name: 'url'
                        label: 'URL'
                        widget: 'object'
                        summary: '{{fields.title}}'
                        fields:
                          - { label: Title, name: title, widget: string}
                          - { label: URL, name: url, widget: string }
      - name: "connect"
        label: "Connect - Mailing List"
        file: "content/connect/_index.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: "Is Draft?", name: "draft", widget: "boolean"}
          - { label: Content, name: body, widget: markdown }
          - label: Side Photo (portrait mode)
            name: photo
            widget: image
            tagname: ''
  - name: "programs"
    label: "Programs"
    delete: false
    files:
      - name: "fallPreschool"
        label: "Fall Programs - Preschool"
        file: "content/programs/fall/preschool/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "table_day" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Session", name: "session", widget: "string" }
          - { label: "Category 1", name: "category1", widget: "string", required: false }
          - { label: "Category 2", name: "category2", widget: "string", required: false }
          - { label: "Category 3", name: "category3", widget: "string", required: false }
          - { label: "Is Draft?", name: "draft", widget: "boolean"}
          - { label: "Minimum Age", name: "minage", widget: "hidden", default: 2 }
          - { label: "Maximum Age", name: "maxage", widget: "hidden", default: 5 }
          - label: Tile Picture
            name: photo
            widget: image
            tagname: ''
      - name: "fallGradeSchool"
        label: "Fall Programs - Grade School"
        file: "content/programs/fall/k-12/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "table_day" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Session", name: "session", widget: "string" }
          - { label: "Category 1", name: "category1", widget: "string", required: false }
          - { label: "Category 2", name: "category2", widget: "string", required: false }
          - { label: "Category 3", name: "category3", widget: "string", required: false }
          - { label: "Is Draft?", name: "draft", widget: "boolean"}
          - { label: "Minimum Age", name: "minage", widget: "hidden", default: 5 }
          - { label: "Maximum Age", name: "maxage", widget: "hidden", default: 18 }
          - label: Tile Picture
            name: photo
            widget: image
            required: false
            tagname: ''
      - name: "fallAdult"
        label: "Fall Programs - Adult"
        file: "content/programs/fall/adult/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "table_day" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Session", name: "session", widget: "string" }
          - { label: "Category 1", name: "category1", widget: "string", required: false }
          - { label: "Category 2", name: "category2", widget: "string", required: false }
          - { label: "Category 3", name: "category3", widget: "string", required: false }
          - { label: "Is Draft?", name: "draft", widget: "boolean"}
          - label: Tile Picture
            name: photo
            widget: image
            required: false
            tagname: ''
      - name: "winter"
        label: "Winter Programs"
        file: "content/programs/winter/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Section Class", name: "sectionClass", widget: "hidden", default: "winter-session"}
          - { label: "Layout", name: "layout", widget: "hidden", default: "table_day" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Session", name: "session", widget: "string" }
          - { label: "Category 1", name: "category1", widget: "string", required: false }
          - { label: "Category 2", name: "category2", widget: "string", required: false }
          - { label: "Category 3", name: "category3", widget: "string", required: false }
          - { label: "Is Draft?", name: "draft", widget: "boolean"}
          - { label: "Minimum Age", name: "minage", widget: "hidden", default: 2 }
          - { label: "Maximum Age", name: "maxage", widget: "hidden", default: 18 }
          - label: Tile Picture
            name: photo
            widget: image
            required: false
            tagname: ''
      - name: "summer"
        label: "Summer Programs"
        file: "content/programs/summer/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Section Class", name: "sectionClass", widget: "hidden", default: "summer-session"}
          - { label: "Layout", name: "layout", widget: "hidden", default: "table" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Session", name: "session", widget: "string" }
          - { label: "Category 1", name: "category1", widget: "string", required: false }
          - { label: "Category 2", name: "category2", widget: "string", required: false }
          - { label: "Category 3", name: "category3", widget: "string", required: false }
          - { label: "Is Draft?", name: "draft", widget: "boolean"}
          - { label: "Minimum Age", name: "minage", widget: "hidden", default: 2 }
          - { label: "Maximum Age", name: "maxage", widget: "hidden", default: 18 }
          - label: Tile Picture
            name: photo
            widget: image
            required: false
            tagname: ''
  - name: "events"
    label: "Regular Events"
    label_singular: "Event"
    folder: "content/events"
    filter: {field: "cms", value: true}
    create: true
    identifier_field: name
    fields:
      - {label: CMS, name: cms, widget: hidden, default: true}
      - {label: Event Name, name: name, widget: string}
      - {label: "Exclude from Sitemap", name: "sitemap_exclude", widget: hidden, default: true }
      - label: Event Picture
        name: photo
        widget: image
        required: false
        tagname: ''
        media_library:
          config:
            default_transformations:
              -   - crop: "fill"
                    gravity: "auto:subject"
                    height: 310
                    width: 310
      - label: "Event Date"
        name: "startdate"
        widget: "datetime"
        required: false
      - {label: Description, name: description, widget: string}
      - {label: Event Info, name: body, widget: markdown}
  - name: "special-events"
    label: "Special Events"
    delete: false
    files:
      - name: "gala"
        label: "Gala"
        file: "content/gala/_index.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Password, name: password, widget: string, required: false }
          - { label: "Is Draft?", name: "draft", widget: "boolean"}
          - {label: "Exclude from Sitemap", name: sitemap_exclude, widget: hidden, default: true }
          - { label: Content, name: body, widget: markdown }
          - name: 'resources'
            label: 'Resources'
            label_singular: 'Resource'
            summary: '{{fields.section.header}}'
            widget: 'list'
            fields:
              - name: 'section'
                label: 'Section'
                widget: object
                fields:
                  - { label: Header, name: header, widget: string }
                  - name: 'items'
                    label: 'Resource Items'
                    label_singular: 'Resource'
                    widget: 'list'
                    types:
                      - name: 'document'
                        label: 'Document'
                        widget: 'object'
                        summary: '{{fields.title}}'
                        fields:
                          - { label: Title, name: title, widget: string}
                          - { label: Document, name: url, widget: file }
                      - name: 'url'
                        label: 'URL'
                        widget: 'object'
                        summary: '{{fields.title}}'
                        fields:
                          - { label: Title, name: title, widget: string}
                          - { label: URL, name: url, widget: string }
      - name: "sdi"
        label: "SDI"
        file: "content/sdi/_index.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Password, name: password, widget: string, required: false }
          - { label: "Is Draft?", name: "draft", widget: "boolean"}
          - {label: "Exclude from Sitemap", name: sitemap_exclude, widget: hidden, default: true }
          - { label: Content, name: body, widget: markdown }
          - name: 'resources'
            label: 'Resources'
            label_singular: 'Resource'
            summary: '{{fields.section.header}}'
            widget: 'list'
            fields:
              - name: 'section'
                label: 'Section'
                widget: object
                fields:
                  - { label: Header, name: header, widget: string }
                  - name: 'items'
                    label: 'Resource Items'
                    label_singular: 'Resource'
                    widget: 'list'
                    types:
                      - name: 'document'
                        label: 'Document'
                        widget: 'object'
                        summary: '{{fields.title}}'
                        fields:
                          - { label: Title, name: title, widget: string}
                          - { label: Document, name: url, widget: file }
                      - name: 'url'
                        label: 'URL'
                        widget: 'object'
                        summary: '{{fields.title}}'
                        fields:
                          - { label: Title, name: title, widget: string}
                          - { label: URL, name: url, widget: string }
  - name: "company"
    label: "Company"
    label_singular: "Company"
    folder: "content/company"
    filter: {field: "cms", value: true}
    create: true
    identifier_field: name
    fields:
      - {label: CMS, name: cms, widget: hidden, default: true}
      - {label: Company Name, name: name, widget: string}
      - {label: "Exclude from Sitemap", name: sitemap_exclude, widget: hidden, default: true }
      - label: Company Picture
        name: photo
        widget: image
        required: false
        tagname: ''
      - {label: Password, name: password, widget: string, required: false}
      - {label: Description, name: description, widget: string}
      - {label: Company Info, name: body, widget: markdown}
      - name: 'resources'
        label: 'Resources'
        label_singular: 'Resource'
        widget: 'list'
        summary: '{{fields.section.header}}'
        fields:
          - name: 'section'
            label: 'Section'
            widget: object
            fields:
              - { label: Header, name: header, widget: string }
              - name: 'items'
                label: 'Resource Items'
                label_singular: 'Resource'
                widget: 'list'
                types:
                  - name: 'document'
                    label: 'Document'
                    widget: 'object'
                    summary: '{{fields.title}}'
                    fields:
                      - { label: Title, name: title, widget: string}
                      - { label: Document, name: url, widget: file }
                  - name: 'url'
                    label: 'URL'
                    widget: 'object'
                    summary: '{{fields.title}}'
                    fields:
                      - { label: Title, name: title, widget: string}
                      - { label: URL, name: url, widget: string }
  - name: "staff"
    label: "Staff"
    label_singular: "Staff"
    folder: "content/staff"
    filter: {field: "cms", value: true}
    create: true
    identifier_field: name
    fields:
      - {label: CMS, name: cms, widget: hidden, default: true}
      - {label: Staff Name, name: name, widget: string}
      - {label: Fun Fact, name: funfact, widget: string, required: false}
      - {label: CCCO Start Date, name: startdate, widget: date, required: false}
      - label: Staff Picture
        name: photo
        widget: image
        required: false
        tagname: ''
      - {label: Job Title, name: job_title, widget: string}
      - {label: "Exclude from Sitemap", name: sitemap_exclude, widget: hidden, default: true }
      - {label: Short Bio, name: body, widget: markdown}
