backend:
  name: git-gateway

publish_mode: editorial_workflow

media_library:
  name: cloudinary
  
  config:
    cloud_name: db2kg6drb
    api_key: 571916794148849
    
media_folder: "static/images/uploads"
public_folder: "images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        file: "content/_index.md"
        fields: 
          - { label: Title, name: title, widget: string }
          - name: "events"
            label: "What's Happening Now?"
            widget: "object"
            fields:
              - name: "event1"
                label: "Event 1"
                required: false
                widget: "relation"
                collection: "events"
                displayFields: ["name"]
                searchFields: ["name"]
                valueField: "name"
              - name: "event2"
                label: "Event 2"
                required: false
                widget: "relation"
                collection: "events"
                displayFields: ["name"]
                searchFields: ["name"]
                valueField: "name"
              - name: "event3"
                label: "Event 3"
                required: false
                widget: "relation"
                collection: "events"
                displayFields: ["name"]
                searchFields: ["name"]
                valueField: "name"
  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "content/events"
    filter: {field: "cms", value: true}
    create: true
    identifier_field: name
    fields:
      - {label: CMS, name: cms, widget: hidden, default: true}
      - {label: Event Name, name: name, widget: string}
      - label: Event Picture
        name: photo
        widget: image
        required: false
        tagname: ''
      - {label: Event Date, name: startdate, widget: datetime}
      - {label: Description, name: description, widget: markdown}
  - name: "staff"
    label: "Staff"
    label_singular: "Staff"
    folder: "content/staff"
    filter: {field: "cms", value: true}
    create: true
    identifier_field: name
    fields:
      - {label: CMS, name: cms, widget: hidden, default: true}
      - {label: Staff Name, name: name, widget: string}
      - label: Staff Picture
        name: photo
        widget: image
        required: false
        tagname: ''
        media_library:
          config:
            default_transformations:
              -   - aspect_ratio: "1:1"
                    crop: "crop"
                  - crop: "limit"
                    width: 300
                  - gravity: "face:center"
                  - radius: "max"
      - {label: Job Title, name: job_title, widget: string}
      - {label: Short Bio, name: body, widget: markdown}
