backend:
  name: git-gateway

publish_mode: editorial_workflow

media_library:
  name: cloudinary
  
  config:
    cloud_name: cc-co-dance-complex
    api_key: 568677699738745
    
media_folder: "static/images/uploads"
public_folder: "images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    delete: false
    files:
      - name: "home"
        label: "Home"
        file: "content/_index.md"
        fields: 
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - label: "Carousel Images"
            name: "galleryImages"
            widget: "list"
            field: 
              label: 'Image'
              name: 'image'
              widget: 'image'
              media_library:
                config:
                  default_transformations:
                    -   - fetch_format: auto
                          quality: auto:best
                          height: 700
                          crop: scale
          - { label: 'About Us content', name: 'aboutUs', widget: 'markdown' }
          - label: "Number of Events"
            name: "eventnum"
            widget: "number"
            valueType: "int"
            default: 3
            min: 0
  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "content/events"
    filter: {field: "cms", value: true}
    create: true
    identifier_field: name
    fields:
      - {label: CMS, name: cms, widget: hidden, default: true}
      - {label: Event Name, name: name, widget: string}
      - label: Event Picture
        name: photo
        widget: image
        required: false
        tagname: ''
      - {label: Event Date, name: startdate, widget: datetime}
      - {label: Description, name: description, widget: markdown}
  - name: "staff"
    label: "Staff"
    label_singular: "Staff"
    folder: "content/staff"
    filter: {field: "cms", value: true}
    create: true
    identifier_field: name
    fields:
      - {label: CMS, name: cms, widget: hidden, default: true}
      - {label: Staff Name, name: name, widget: string}
      - label: Staff Picture
        name: photo
        widget: image
        required: false
        tagname: ''
        media_library:
          config:
            default_transformations:
              -   - aspect_ratio: "1:1"
                    crop: "crop"
                  - crop: "limit"
                    width: 300
                  - gravity: "face:center"
      - {label: Job Title, name: job_title, widget: string}
      - {label: Short Bio, name: body, widget: markdown}
