backend:
  name: git-gateway

publish_mode: editorial_workflow

media_library:
  name: cloudinary

  config:
    cloud_name: cc-co-dance-complex
    api_key: 568677699738745

media_folder: "static/images/uploads"
public_folder: "images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    delete: false
    files:
      - name: "home"
        label: "Home"
        file: "content/_index.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - label: "Carousel Images"
            name: "galleryImages"
            widget: "list"
            field:
              label: 'Image'
              name: 'image'
              widget: 'image'
              media_library:
                config:
                  default_transformations:
                    -   - fetch_format: auto
                          quality: auto:best
                          height: 700
                          crop: scale
          - { label: 'About Us content', name: 'aboutUs', widget: 'markdown' }
          - label: "Number of Events"
            name: "eventnum"
            widget: "number"
            valueType: "int"
            default: 3
            min: 0
  - name: "programs"
    label: "Programs"
    delete: false
    files:
      - name: "fallPreschool"
        label: "Fall Programs - Preschool"
        file: "content/programs/fall/preschool/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "table" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Session", name: "session", widget: "string" }
          - { label: "Category 1", name: "category1", widget: "string", required: false }
          - { label: "Category 2", name: "category2", widget: "string", required: false }
          - { label: "Category 3", name: "category3", widget: "string", required: false }
          - { label: "Minimum Age", name: "minage", widget: "hidden", default: 2 }
          - { label: "Maximum Age", name: "maxage", widget: "hidden", default: 5 }
          - label: Tile Picture
            name: photo
            widget: image
            tagname: ''
            media_library:
              config:
                default_transformations:
                  -   - crop: "fill"
                        gravity: "center"
                        height: 400
                        width: 400
                      - background: "rgb:000000"
                        effect: "gradient_fade"
                        y: -0.50
                      - overlay: "text:overpass_42_style_bold_align_center:Preschool"
                        color: "rgb:ffffff"
                        width: 0.75
                        y: 0.3
      - name: "fallGradeSchool"
        label: "Fall Programs - Grade School"
        file: "content/programs/fall/k-12/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "table" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Session", name: "session", widget: "string" }
          - { label: "Category 1", name: "category1", widget: "string", required: false }
          - { label: "Category 2", name: "category2", widget: "string", required: false }
          - { label: "Category 3", name: "category3", widget: "string", required: false }
          - { label: "Minimum Age", name: "minage", widget: "hidden", default: 5 }
          - { label: "Maximum Age", name: "maxage", widget: "hidden", default: 18 }
          - label: Tile Picture
            name: photo
            widget: image
            required: false
            tagname: ''
            media_library:
              config:
                default_transformations:
                  -   - crop: "fill"
                        gravity: "center"
                        height: 400
                        width: 400
                      - background: "rgb:000000"
                        effect: "gradient_fade"
                        y: -0.50
                      - overlay: "text:overpass_42_style_bold_align_center:Grade%20School"
                        color: "rgb:ffffff"
                        width: 0.75
                        y: 0.3
      - name: "fallAdult"
        label: "Fall Programs - Adult"
        file: "content/programs/fall/adult/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "table" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Session", name: "session", widget: "string" }
          - { label: "Category 1", name: "category1", widget: "string", required: false }
          - { label: "Category 2", name: "category2", widget: "string", required: false }
          - { label: "Category 3", name: "category3", widget: "string", required: false }
          - label: Tile Picture
            name: photo
            widget: image
            required: false
            tagname: ''
            media_library:
              config:
                default_transformations:
                  -   - crop: "fill"
                        gravity: "center"
                        height: 400
                        width: 400
                      - background: "rgb:000000"
                        effect: "gradient_fade"
                        y: -0.50
                      - overlay: "text:overpass_42_style_bold_align_center:Adult%20Classes"
                        color: "rgb:ffffff"
                        width: 0.75
                        y: 0.3
      - name: "winter"
        label: "Winter Programs"
        file: "content/programs/winter/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "table" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Session", name: "session", widget: "string" }
          - { label: "Category 1", name: "category1", widget: "string", required: false }
          - { label: "Category 2", name: "category2", widget: "string", required: false }
          - { label: "Category 3", name: "category3", widget: "string", required: false }
          - { label: "Minimum Age", name: "minage", widget: "hidden", default: 2 }
          - { label: "Maximum Age", name: "maxage", widget: "hidden", default: 18 }
          - label: Tile Picture
            name: photo
            widget: image
            required: false
            tagname: ''
            media_library:
              config:
                default_transformations:
                  -   - crop: "fill"
                        gravity: "center"
                        height: 400
                        width: 400
                      - background: "rgb:000000"
                        effect: "gradient_fade"
                        y: -0.50
                      - overlay: "text:overpass_42_style_bold_align_center:Winter%20Classes"
                        color: "rgb:ffffff"
                        width: 0.75
                        y: 0.3
  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "content/events"
    filter: {field: "cms", value: true}
    create: true
    identifier_field: name
    fields:
      - {label: CMS, name: cms, widget: hidden, default: true}
      - {label: Event Name, name: name, widget: string}
      - label: Event Picture
        name: photo
        widget: image
        required: false
        tagname: ''
        media_library:
          config:
            default_transformations:
              -   - crop: "fill"
                    gravity: "auto:subject"
                    height: 310
                    width: 310
      - label: "Event Date"
        name: "startdate"
        widget: "datetime"
      - {label: Description, name: description, widget: string}
      - {label: Event Info, name: body, widget: markdown}
  - name: "company"
    label: "Company"
    label_singular: "Company"
    folder: "content/company"
    filter: {field: "cms", value: true}
    create: true
    identifier_field: name
    fields:
      - {label: CMS, name: cms, widget: hidden, default: true}
      - {label: Company Name, name: name, widget: string}
      - label: Company Picture
        name: photo
        widget: image
        required: false
        tagname: ''
      - {label: Password, name: password, widget: string}
      - {label: Description, name: description, widget: string}
      - {label: Company Info, name: body, widget: markdown}
      - label: Resources
        name: resources
        widget: object
        fields:
        - label: "Forms"
          name: forms
          widget: list
          fields:
            - {label: Title, name: form_title, widget: string}
            - {label: URL: name: form_url, widget: string}
        - label: "General Information"
          name: general_info
          widget: list
          fields:
            - {label: Title, name: file_title, widget: string}
            - label: File
              name: file_path
              widget: file
        - label: "Guidelines"
          name: guidelines
          widget: list
          fields:
            - {label: Title, name: file_title, widget: string}
            - label: File
              name: file_path
              widget: file
        - label: "S/D/T Guidelines"
          name: sdt_guidelines
          widget: list
          fields:
            - {label: Title, name: file_title, widget: string}
            - label: File
              name: file_path
              widget: file
        - label: "Schedule"
          name: schedule
          widget: list
          fields:
            - {label: Title, name: file_title, widget: string}
            - label: File
              name: file_path
              widget: file
  - name: "staff"
    label: "Staff"
    label_singular: "Staff"
    folder: "content/staff"
    filter: {field: "cms", value: true}
    create: true
    identifier_field: name
    fields:
      - {label: CMS, name: cms, widget: hidden, default: true}
      - {label: Staff Name, name: name, widget: string}
      - label: Staff Picture
        name: photo
        widget: image
        required: false
        tagname: ''
        media_library:
          config:
            default_transformations:
              -   - aspect_ratio: "1:1"
                    crop: "crop"
                  - crop: "limit"
                    width: 300
                  - gravity: "face:center"
      - {label: Job Title, name: job_title, widget: string}
      - {label: Short Bio, name: body, widget: markdown}
